name: Linux build develop

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
    
jobs:
  test-build:
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    steps:
      - name: Clone QuickQanava
        uses: actions/checkout@v2
        with:
          ref: develop

      #- name: Cache Qt
      #  id: cache-qt
      #  uses: actions/cache@v1
      #  with:
      #    path: ../Qt
      #    key: ubuntu-latest-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          #cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: qtcore qttools qtgui qtquickcontrols2
          version: 5.15.2
          target: desktop
          #setup-python: false

      - name: Create Build Dir
        run: mkdir build
        working-directory: ${{runner.workspace}}
        
      - name: Configure qmake
        run: |
          QT_SELECT=5 qmake CONFIG+=release -spec linux-g++-64 -makefile -o Makefile ${GITHUB_WORKSPACE}/quickqanava.pro          
        working-directory: ${{runner.workspace}}/build
        shell: bash

      - name: Build Project
        run: make -j$(nproc)
        working-directory: ${{runner.workspace}}/build
